<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License BY-NC-ND.
 * NonCommercial — You may not use the material for commercial purposes.
 * NoDerivatives — If you remix, transform, or build upon the material,
 * you may not distribute the modified material.
 * See the full license at http://creativecommons.org/licenses/by-nc-nd/4.0/
 *
 * See http://mventory.com/legal/licensing/ for other licensing options.
 *
 * @package MVentory/TradeMe
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://creativecommons.org/licenses/by-nc-nd/4.0/
 */

?>

<div class="trademe-setting-hint">
  List products on TradeMe from Magento Admin, Android app or using a cron. Sync stock levels and much more.
  <br />
  See <a target="_blank" href="https://github.com/mVentory/MVentory_TradeMe/">project page</a> for documentation and source code. Check out our <a target="_blank" href="http://mventory.com/why-mventory/">Android app</a> for Magento admin.
</div>
